### ISSUE TITLE
The /hello command will not work for console

### ISSUE THREAD

**Issue by jakeob28** [Nodifly/NotiPlug#1]
@Nodifly I understand this is your first plugin, so I will just give you a tip to avoid errors.

If you try running the /hello command from console, you will get a error. 
This is because `Player p = (Player) sender` will only work if the sender is a player.
To fix that, you can add
`if (!(sender instanceof Player)) {`
`  sender.sendMessage("This command cannot be run from console")`
`  return true;`
`}`

This bit of code will basically prevent the console from running the command, so you do not get an error. If you want the console to be able to run the command, delete ` Player p = (Player) sender ` and just use `sender.sendMessage("Why hello there!");`

Hope this helps!
If you need any more help with bukkit/spigot programming,  I'm happy to help
Good luck on learning Java and the Spigot API!

**Comment by Nodifly** [comment]
Thanks :) Much appreciated!

**Comment by jakeob28** [comment]
I closed the issue, as it was fixed.
